### ISSUE TITLE
Install docker-compose at 鲲鹏

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/websoft9#14]
Can install Docker-compose at 鲲鹏 by pip?

**Comment by chendelin1982** [comment]
There no Python3, need intall python3 first
```
yum install python3
pip3 install --upgrade setuptools
pip3 install --upgrade pip
pip3 install docker-compose 
```

**Comment by chendelin1982** [comment]
pip3 install mysql also error
```
[root@ecs-c5a4 ~]# pip3 install mysql
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting mysql
  Using cached https://files.pythonhosted.org/packages/9a/52/8d29c58f6ae448a72fbc612955bd31accb930ca479a7ba7197f4ae4edec2/mysql-0.0.3-py3-none-any.whl
Collecting mysqlclient (from mysql)
  Using cached https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1xbtgqz6/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-1xbtgqz6/mysqlclient/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-build-1xbtgqz6/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1xbtgqz6/mysqlclient/
```

**Comment by chendelin1982** [comment]
refer to: [鲲鹏开发套件](https://support.huaweicloud.com/function-kunpengdevps/function-kunpengdevps.html)

**Comment by chendelin1982** [comment]
Solution: Docker-compose have provide aarc64-linux for download: https://github.com/docker/compose/releases/tag/v2.1.1
![image](https://user-images.githubusercontent.com/16741975/142127618-04928506-e464-40d9-a442-252369a02df3.png)

I have test it, it can running on Kunpeng 920
