### ISSUE TITLE
There is python3 in the Amazonlinux, but it have not requests module.

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/websoft9#400]
```
[Plugins] -  Starting download plugin and update it
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests
```

**Comment by qiaofeng1227** [comment]
```
for module in "${modules[@]}"
do
    python3 -c "import $module" &> /dev/null
    if [ $? -ne 0 ]; then
        echo "Installing $module"
        pip3 install $module
    fi
done
```

**Comment by qiaofeng1227** [comment]
```
[Plugins] -  Starting download plugin and update it
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.7/site-packages/urllib3/__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
Plugins install successfully...
Restart Docker for Firewalld...
```

**Comment by chendelin1982** [comment]
jq -c . input.json > output.json
